spring.datasource.url=jdbc:postgresql://localhost:5432/incentivosdb
spring.datasource.username=ddsi
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.devtools.restart.enabled=true

server.port=${PORT:8080}