spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/incentivosdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ddsi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=6582e3eb87a362aa3e283b7e48be1c60
management.metrics.export.datadog.step=30s
management.metrics.tags.application=incentivos

spring.devtools.restart.enabled=true

server.port=${PORT:8080}

donadores.url=${DONADORES_URL:http://localhost:8081}
donaciones.url=${DONACIONES_URL:http://localhost:8082}
logistica.url=${LOGISTICA_URL:http://localhost:8083}